#!/usr/bin/env sh
. "$(dirname "$0")/_/husky.sh"

if [[ $(git diff --cached --name-only --diff-filter=ACM | grep -E "\.(js|ts|jsx|tsx)$") = "" ]]; then
  exit 0
fi

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E "\.(js|ts|jsx|tsx)$")
PASS=true

echo "🔄 Validating Javascript:"

yarn eslint ${STAGED_FILES[*]} "$@"

if [ $? -ne 0 ]; then
    echo "❌ ESLint Failed"
    PASS=false
    exit 1
fi

echo "🏁 Javascript validation completed!"

if ! $PASS; then
  echo "✅ COMMIT SUCCEEDED"
fi

exit $?
